learning_log/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^users/', include(('users.urls', 'users'), namespace='users')),
    re_path(r'', include(('learnings_logs.urls','learnings_logs'), namespace='learnings_logs')),
]

learnings_logs/urls.py
"""Определяет схемы URL для learning_logs """

from django.conf.urls import url

from . import views

urlpatterns = [
    # Домашняя стр
    url(r'^$', views.index, name='index'),
    # Вывод тем
    url(r'^topics/$', views.topics, name='topics'),
    # Страница с подбробной информацией по отдельной теме
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topics/$', views.new_topics, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

]

users/urls.py
from django.conf.urls import url

from django.contrib.auth.views import LoginView

from . import views
urlpatterns = [

    url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),

]

learnings_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """Тема которую изучает пользователь"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        '''Возвращает строково представление модели.'''
        return self.text

class Entry(models.Model):
    """Информация, изученная пользователем по теме"""
    # ссылается на другую запись в базе данных
    topic = models.ForeignKey(Topic, on_delete=models.DO_NOTHING)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        '''Возвращает строковое представление модели'''
        return self.text[:50] + '...' if len(self.text) > 50 else self.text[:50]

users/models.py
from django.db import models

# Create your models here.

learnings_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learnings_logs/views.py
from django.shortcuts import render
from .models import Topic
from django.http import HttpResponseRedirect

from django.http import HttpResponseRedirect, Http404

from django.contrib.auth.decorators import login_required

from django.urls import reverse

from .forms import TopicForm, EntryForm, Entry
# Create your views here.

def check_topic_owner(topic, request):
    if topic.owner != request.user:
        raise Http404

def index(request):
    """Жомашняя страница приложения LL"""
    return render(request, 'learnings_logs/index.html')

@login_required
def topics(request):
    '''Выводим список тем'''
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learnings_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    ''' Выводит одну тему и все ее записи'''
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic, request)
    # знак - сортирует запсии в обратном порядке
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learnings_logs/topic.html', context)

@login_required
def new_topics(request):
    # Орпдееляет новую тему
    if request.method != 'POST':
        # Данные не отпрвалялись, создается форма
        form = TopicForm()
    else:
        # Отправлены данные ПОСТ , обработать данные
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learnings_logs:topics'))
    context = {'form': form}
    return render(request, 'learnings_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    # Добавляет новую запись по конкретной теме
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic, request)

    if request.method != 'POST':
        #Данные не отправлялись, создается пустая форма
        form = EntryForm()
    else:
        # Отправляем данные ПОСТ , обработтаь данные
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learnings_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learnings_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    # Редактирует существующую запись
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(topic, request)

    if request.method != 'POST':
        # исходный апрос. форма заполеняется данными текущей записи
        form = EntryForm(instance=entry)
    else:
        # Отправка данных пост. обработать данные
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learnings_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learnings_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learnings_logs:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticateed_user = authenticate(username=new_user.username, password = request.POST['password1'])
            login(request, authenticateed_user)
            return HttpResponseRedirect(reverse('learnings_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learnings_logs/templates/learnings_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="'utf-8">
        <meta http-equiv="X-UA-Compatible" content="'IE=edge">
        <meta name="'viewport" content="width=device-width, initial-scale=1">

        <title>Learning Log</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
<!--        Статическая навигационная панел-->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse " data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'learnings_logs:index' %}">
                    Learning Log
                </a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learnings_logs:topics' %}">Topics</a> </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                     {% if user.is_authenticated %}
                        <li><a>Hello, {{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">Log out</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">register</a></li>
                        <li><a href="{% url 'users:login' %}">log in</a></li>
                    {% endif %}
                </ul>
            </div> <!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div> <!-- /container -->

    </body>

learnings_logs/templates/learnings_logs/edit_entry.html
{% extends "learnings_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2><a href="{% url 'learnings_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock header %}


{% block content %}

    <h3>Edit entry:</h3>

    <form action="{% url 'learnings_logs:edit_entry' entry.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">save changes</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learnings_logs/templates/learnings_logs/index.html
{% extends "learnings_logs/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>Track your learnings.</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{url 'users:regiter'}">Register an account</a>
        tp make your own Learnings Log, and list the topics you're learning about.
    </h2>
    <h2>
        Повседневная практика показывает, что укрепление и развитие структуры обеспечивает широкому кругу (специалистов) участие в формировании дальнейших направлений развития. Повседневная практика показывает, что укрепление и развитие структуры обеспечивает широкому кругу (специалистов) участие в формировании дальнейших направлений развития.
    </h2>

{% endblock content %}

learnings_logs/templates/learnings_logs/new_entry.html
{% extends "learnings_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2><a href="{% url 'learnings_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock header %}


{% block content %}

    <h3>Add new entry:</h3>

    <form action="{% url 'learnings_logs:new_entry' topic.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">add entry</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learnings_logs/templates/learnings_logs/new_topic.html
{% extends "learnings_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'learnings_logs:new_topic' %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learnings_logs/templates/learnings_logs/topic.html
{% extends 'learnings_logs/base.html' %}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}

  <p>
      <a href="{% url 'learnings_logs:new_entry' topic.id %}">add new entry</a>
  </p>

    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'learnings_logs:edit_entry' entry.id %}">edit entry</a>
                    </small>
                </h3>
            </div>
        <div class="panel-body">
            {{ entry.text|linebreaks }}
        </div>
        </div> <!-- panel -->


       {% empty %}

        There are no entries for this topic.

    {% endfor %}

{% endblock content %}

learnings_logs/templates/learnings_logs/topics.html
{% extends "learnings_logs/base.html"%}

{% block header %}
    <h1>Topics</h1>
{% endblock header %}

{% block content %}

    <ul>
    {% for topic in topics %}
    <li>
        <h3>
            <a href="{% url 'learnings_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
    </li>
    {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
    </ul>

<h3><a href="{% url 'learnings_logs:new_topic' %}">Add new topic:</a></h3>

{% endblock content %}

users/templates/users/login.html
{% extends "learnings_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">log in</button>
        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'learnings_logs:index' %}"/>
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "learnings_logs/base.html" %}
{% load bootstrap3 %}


{% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Register</button>
        {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'learnings_logs:index' %}"/>

    </form>
{% endblock content %}